name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write  # Added for workflow cancellation

# Allow only one concurrent deployment, cancelling in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: "https://mkdevelopment1312.github.io/pwa-hotel/"
    runs-on: ubuntu-latest
    
    steps:
    - name: Cancel Previous Deployments
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        workflow_id: ${{ github.workflow }}
        access_token: ${{ github.token }}
        
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Verify build
      run: npm run verify
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Wait for any pending deployments
      run: |
        echo "Waiting 90 seconds for any pending deployments to complete..."
        sleep 90
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        timeout: 900000  # 15 minutes
        error_count: 20  # More retries
        reporting_interval: 10000
